project:
   type: book
   output-dir: ../docs

book:
   title: "Assessment of fisheries impact in the Dutch part of the Northsea, for 2009. The Bfiat approach"
   reader-mode: true
   page-footer:
     left: |
       written by Karline Soetaert.
     right: |
       for the EMODnet biology project
   cover-image: logo_hex.png
   chapters:
     - index.qmd
     - 01_BFIAT_data.qmd
     - 02_BFIAT_analysis.qmd
     - 03_BFIAT_maps.qmd
     - 04_BFIAT_netCDF.qmd
     - references.qmd
     
author: "karline soetaert"
toc: true
toc-depth: 3
toc-expand: true

code-fold: show

format:
  html:
    theme:
      - cosmo
      - quarto-tdg.scss
    author-meta: "Karline Soetaert"
    callout-appearance: simple
    highlight-style: a11y

execute:
  echo: true
  warning: false
  message: false
editor: 
  markdown: 
    wrap: sentence
   